default:
  image: node:20.11.1

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --debug --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --debug --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --debug --token=$VERCEL_TOKEN
